#+TITLE XOR: A mashup of 8-bit space exploration and combat games

* Overview

In the game of XOR, a single player controls an interstellar combat
ship from a 2-D overhead perspective. The world map is a "galactic
grid" with each square having one of a number of procedurally
generated level types (empty space, planet surface, clouds, enemy
convoy, enemy star cruiser, starbase/trading post). A randomly
generated mission (between 10-30 minutes depending on difficulty) will
have you visiting one or more areas, defeating enemies, or retrieving
specific objects in order to win.

The arrow keys (or WSAD) move the ship, and the mouse is used to aim
and fire the weapon (as in Paradroid). Left clicking fires at the
point under the mouse cursor; right-clicking (or shift-clicking)
instead activates any object under the cursor. Objects can be picked
up by flying over them.

There are two resources that must be managed. ENERGY is used when you
fire weapons or travel between sectors, and is also needed to activate
certain objects in the game world. The game will end if your SHIELD
rating drops to zero. In addition, a limited number of special items
may be carried.

There are three difficulty levels: BASIC, ADVANCED, and EXPERT. For
BASIC, a mission should be about 10 minutes long; EXPERT games may be
as long as 30 minutes. (Your character is not saved---the point is to
experience different stories with disposable characters, with each
story having a few discrete goals and an objectively scored outcome.)

The sound will consist of subtle engine hisses and hums and quiet
drones with contextual musical clues. I'm planning to use FM synthesis
(Hexter) and also Milkytracker.

Collecting items, energy, and minerals will be a significant play
activity, along with dogfights against 1-3 enemies at a time.
